### PR TITLE
Initialize offline storage on main thread before snapshotting

### LINKED ISSUE #227: Uncaught exception starting MGLMapSnapshotter before using MGLMapView or MGLOfflineStorage
If an application attempts to take a snapshot before ever initializing an MGLMapView or interacting with MGLOfflineStorage directly, `-[MGLMapSnapshotter startWithQueue:overlayHandler:completionHandler:]` raises an exception:

https://github.com/mapbox/mapbox-gl-native-ios/blob/81df48df70ad6b116f3f17321d11a56a03b3cc3e/platform/darwin/src/MGLMapSnapshotter.mm#L267-L270

This check is premature, since the method soon afterwards causes MGLOfflineStorage to create an `mbgl::util::RunLoop` and various file sources on the current thread:

https://github.com/mapbox/mapbox-gl-native-ios/blob/81df48df70ad6b116f3f17321d11a56a03b3cc3e/platform/darwin/src/MGLMapSnapshotter.mm#L285 https://github.com/mapbox/mapbox-gl-native-ios/blob/81df48df70ad6b116f3f17321d11a56a03b3cc3e/platform/darwin/src/MGLMapSnapshotter.mm#L664 https://github.com/mapbox/mapbox-gl-native-ios/blob/81df48df70ad6b116f3f17321d11a56a03b3cc3e/platform/darwin/src/MGLOfflineStorage.mm#L64 https://github.com/mapbox/mapbox-gl-native-ios/blob/81df48df70ad6b116f3f17321d11a56a03b3cc3e/platform/darwin/src/MGLOfflineStorage.mm#L223 https://github.com/mapbox/mapbox-gl-native-ios/blob/81df48df70ad6b116f3f17321d11a56a03b3cc3e/platform/darwin/src/MGLFoundation.mm#L5

If we were to simply remove or defer this check, the check would pass even if starting the snapshotter on a background thread. However, the static `mbgl::util::RunLoop` intended for the main thread would be created for a background thread, which would lead to undefined behavior, for example when subsequently using MGLMapView.

Before #210, the same application didn’t trigger the exception because `-[MGLMapSnapshotter initWithOptions:]` happened to call `-setOptions:`, which called `+[MGLOfflineStorage sharedOfflineStorage]` before the run loop check. Even so, if a developer happened to initialize the snapshotter on a background thread, the static `RunLoop` intended for the main thread would’ve been created on the background thread.

One potential fix would be to call `+[MGLOfflineStorage sharedOfflineStorage]` in `+[MGLMapSnapshotter initialize]`, but that could potentially impact startup time even in applications that don’t use MGLMapSnapshotter earlly on. Another fix would be to replace the existing check with one that explicitly raises an exception if it’s on a background thread but calls `+[MGLOfflineStorage sharedOfflineStorage]` if it’s on the main thread.

Thanks to @julianrex for spotting and helping to diagnose this issue.

/cc @mapbox/maps-ios @alexshalamov

### PR DESCRIPTION
**Pull request by 1ec5**
Ensure that offline storage has been initialized on the main thread, as MGLMapView and MGLOfflineStorage do when used directly. This fixes a regression introduced in #210 as well as fixing some potential undefined behavior from previous releases if MGLMapSnapshotter had been used on a background thread before any direct MGLOfflineStorage or MGLMapView usage.

Fixes #227.

/cc @mapbox/maps-ios

### CODE REVIEW

File: platform/darwin/src/MGLMapSnapshotter.mm [hunk 1]
```diff
@@ -301,7 +301,12 @@ - (void)startWithQueue:(dispatch_queue_t)queue overlayHandler:(MGLMapSnapshotOve
...
     }
-    if (!mbgl::Scheduler::GetCurrent()) {
+    
+    // Ensure that offline storage has been initialized on the main thread, as MGLMapView and MGLOfflineStorage do when used directly.
+    // https://github.com/mapbox/mapbox-gl-native-ios/issues/227
+    if ([NSThread.currentThread isMainThread]) {
+        (void)[MGLOfflineStorage sharedOfflineStorage];
+    } else {
         [NSException raise:NSInvalidArgumentException
                     format:@"startWithQueue:completionHandler: must be called from a thread with an active run loop."];
```
Comment (nishant-karajgikar) [inline platform/darwin/src/MGLMapSnapshotter.mm:311]: Should we change this exception to something like "startWithQueue:completionHandler: must be called from main thread."

Comment (1ec5) [reply platform/darwin/src/MGLMapSnapshotter.mm:311]: Good catch. This reminds me that we have an `MGLAssertIsMainThread()` macro, but I think we do want to raise an exception explicitly (across all build configurations) instead of potentially only asserting in Debug.
